import {
  Department,
  User,
  LeaveRequest,
  BriefingSession,
  AttendanceRecord,
  Notification,
  EmailLog,
  NotificationTemplate,
  AuditLog,
} from '../types';

export const initialDepartments: Department[] = [
  {
    id: 'dept-eng',
    name: 'Engineering & IT',
    code: 'ENG',
    description: 'Software development, infrastructure, and IT security systems.',
    headUserEmail: 'david.chen@acmecorp.com',
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'dept-hr',
    name: 'Human Resources',
    code: 'HR',
    description: 'Talent acquisition, employee welfare, and corporate compliance.',
    headUserEmail: 'maria.santos@acmecorp.com',
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'dept-ops',
    name: 'Operations & Logistics',
    code: 'OPS',
    description: 'Facility operations, supply chain management, and vendor relations.',
    headUserEmail: 'michael.brown@acmecorp.com',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'dept-mkt',
    name: 'Marketing & Growth',
    code: 'MKT',
    description: 'Brand strategy, digital communications, and customer expansion.',
    headUserEmail: 'jessica.taylor@acmecorp.com',
    createdAt: '2026-01-20T08:00:00Z',
  },
];

export const initialUsers: User[] = [
  {
    id: 'usr-admin',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@acmecorp.com',
    googleId: 'goog_1001',
    departmentId: 'dept-hr',
    departmentName: 'Human Resources',
    role: 'Admin',
    status: 'Active',
    createdAt: '2026-01-10T09:00:00Z',
    lastLoginAt: '2026-07-31T01:30:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-super-eng',
    name: 'David Chen',
    email: 'david.chen@acmecorp.com',
    googleId: 'goog_1002',
    departmentId: 'dept-eng',
    departmentName: 'Engineering & IT',
    role: 'Super User',
    status: 'Active',
    createdAt: '2026-01-11T09:00:00Z',
    lastLoginAt: '2026-07-30T16:20:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-super-hr',
    name: 'Maria Santos',
    email: 'maria.santos@acmecorp.com',
    googleId: 'goog_1003',
    departmentId: 'dept-hr',
    departmentName: 'Human Resources',
    role: 'Super User',
    status: 'Active',
    createdAt: '2026-01-12T09:00:00Z',
    lastLoginAt: '2026-07-29T11:15:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-normal-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@acmecorp.com',
    googleId: 'goog_1004',
    departmentId: 'dept-eng',
    departmentName: 'Engineering & IT',
    role: 'Normal User',
    status: 'Active',
    createdAt: '2026-02-01T09:00:00Z',
    lastLoginAt: '2026-07-31T00:45:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-normal-2',
    name: 'Emily Wong',
    email: 'emily.wong@acmecorp.com',
    googleId: 'goog_1005',
    departmentId: 'dept-eng',
    departmentName: 'Engineering & IT',
    role: 'Normal User',
    status: 'Active',
    createdAt: '2026-02-05T09:00:00Z',
    lastLoginAt: '2026-07-28T14:10:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-normal-3',
    name: 'Michael Brown',
    email: 'michael.brown@acmecorp.com',
    googleId: 'goog_1006',
    departmentId: 'dept-ops',
    departmentName: 'Operations & Logistics',
    role: 'Normal User',
    status: 'Active',
    createdAt: '2026-02-10T09:00:00Z',
    lastLoginAt: '2026-07-30T10:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-normal-4',
    name: 'Jessica Taylor',
    email: 'jessica.taylor@acmecorp.com',
    googleId: 'goog_1007',
    departmentId: 'dept-mkt',
    departmentName: 'Marketing & Growth',
    role: 'Normal User',
    status: 'Active',
    createdAt: '2026-03-01T09:00:00Z',
    lastLoginAt: '2026-07-25T15:30:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-normal-5',
    name: 'Robert Kim',
    email: 'robert.kim@acmecorp.com',
    googleId: 'goog_1008',
    departmentId: 'dept-eng',
    departmentName: 'Engineering & IT',
    role: 'Normal User',
    status: 'Active',
    createdAt: '2026-03-15T09:00:00Z',
    lastLoginAt: '2026-07-27T09:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: 'lv-101',
    userId: 'usr-normal-1',
    userName: 'Alex Rivera',
    userEmail: 'alex.rivera@acmecorp.com',
    departmentId: 'dept-eng',
    departmentName: 'Engineering & IT',
    leaveType: 'Annual Leave',
    startDate: '2026-08-04',
    endDate: '2026-08-06',
    dayOption: 'Full Day',
    totalDays: 3,
    reason: 'Family vacation travel.',
    status: 'Approved',
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-07-21T14:30:00Z',
    reviewedBy: 'David Chen',
    reviewedAt: '2026-07-21T14:30:00Z',
    reviewRemarks: 'Approved as coverage is arranged.',
  },
  {
    id: 'lv-102',
    userId: 'usr-normal-2',
    userName: 'Emily Wong',
    userEmail: 'emily.wong@acmecorp.com',
    departmentId: 'dept-eng',
    departmentName: 'Engineering & IT',
    leaveType: 'Medical Leave',
    startDate: '2026-08-05',
    endDate: '2026-08-05',
    dayOption: 'Full Day',
    totalDays: 1,
    reason: 'Dental surgery appointment.',
    status: 'Approved',
    createdAt: '2026-07-25T11:20:00Z',
    updatedAt: '2026-07-26T09:15:00Z',
    reviewedBy: 'David Chen',
    reviewedAt: '2026-07-26T09:15:00Z',
    reviewRemarks: 'Medical certificate submitted.',
  },
  {
    id: 'lv-103',
    userId: 'usr-normal-1',
    userName: 'Alex Rivera',
    userEmail: 'alex.rivera@acmecorp.com',
    departmentId: 'dept-eng',
    departmentName: 'Engineering & IT',
    leaveType: 'Childcare Leave',
    startDate: '2026-08-14',
    endDate: '2026-08-14',
    dayOption: 'Half Day (AM)',
    totalDays: 0.5,
    reason: 'Child school orientation.',
    status: 'Submitted',
    createdAt: '2026-07-29T16:00:00Z',
    updatedAt: '2026-07-29T16:00:00Z',
  },
  {
    id: 'lv-104',
    userId: 'usr-normal-3',
    userName: 'Michael Brown',
    userEmail: 'michael.brown@acmecorp.com',
    departmentId: 'dept-ops',
    departmentName: 'Operations & Logistics',
    leaveType: 'Off-in-lieu',
    startDate: '2026-08-10',
    endDate: '2026-08-11',
    dayOption: 'Full Day',
    totalDays: 2,
    reason: 'Compensatory leave for weekend warehouse deployment.',
    status: 'Submitted',
    createdAt: '2026-07-30T08:30:00Z',
    updatedAt: '2026-07-30T08:30:00Z',
  },
  {
    id: 'lv-105',
    userId: 'usr-super-eng',
    userName: 'David Chen',
    userEmail: 'david.chen@acmecorp.com',
    departmentId: 'dept-eng',
    departmentName: 'Engineering & IT',
    leaveType: 'Annual Leave',
    startDate: '2026-08-20',
    endDate: '2026-08-22',
    dayOption: 'Full Day',
    totalDays: 3,
    reason: 'Personal leave.',
    status: 'Approved',
    createdAt: '2026-07-15T10:00:00Z',
    updatedAt: '2026-07-16T11:00:00Z',
    reviewedBy: 'Sarah Jenkins',
    reviewedAt: '2026-07-16T11:00:00Z',
  },
];

export const initialBriefingSessions: BriefingSession[] = [
  {
    id: 'brf-201',
    title: 'Q3 System Security & Compliance Briefing',
    departmentId: 'dept-eng',
    departmentName: 'Engineering & IT',
    dateTime: '2026-08-05T09:30:00',
    location: 'Conference Room 3A & Google Meet',
    isOnline: true,
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    createdByUserId: 'usr-super-eng',
    createdByName: 'David Chen',
    status: 'Planned',
    notes: 'Mandatory session on multi-factor authentication policies and cloud architecture.',
    createdAt: '2026-07-25T10:00:00Z',
  },
  {
    id: 'brf-202',
    title: 'DevOps Infrastructure Update Briefing',
    departmentId: 'dept-eng',
    departmentName: 'Engineering & IT',
    dateTime: '2026-07-28T14:00:00',
    location: 'Engineering Hub - 4th Floor',
    isOnline: false,
    createdByUserId: 'usr-super-eng',
    createdByName: 'David Chen',
    status: 'Completed',
    notes: 'Review of CI/CD pipeline automation and Docker deployment standards.',
    createdAt: '2026-07-20T09:00:00Z',
  },
  {
    id: 'brf-203',
    title: 'Mid-Year Benefits & Wellness Orientation',
    departmentId: 'dept-hr',
    departmentName: 'Human Resources',
    dateTime: '2026-08-08T11:00:00',
    location: 'Main Auditorium',
    isOnline: true,
    meetingLink: 'https://meet.google.com/xyz-hr-well',
    createdByUserId: 'usr-super-hr',
    createdByName: 'Maria Santos',
    status: 'Planned',
    notes: 'Overview of revised healthcare insurance benefits and remote work stipends.',
    createdAt: '2026-07-26T14:00:00Z',
  },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    id: 'att-301',
    briefingSessionId: 'brf-202',
    userId: 'usr-super-eng',
    userName: 'David Chen',
    userEmail: 'david.chen@acmecorp.com',
    departmentId: 'dept-eng',
    status: 'Present',
    remarks: 'Session Host',
    markedByUserId: 'usr-super-eng',
    markedByName: 'David Chen',
    markedAt: '2026-07-28T15:00:00Z',
  },
  {
    id: 'att-302',
    briefingSessionId: 'brf-202',
    userId: 'usr-normal-1',
    userName: 'Alex Rivera',
    userEmail: 'alex.rivera@acmecorp.com',
    departmentId: 'dept-eng',
    status: 'Present',
    remarks: '',
    markedByUserId: 'usr-super-eng',
    markedByName: 'David Chen',
    markedAt: '2026-07-28T15:00:00Z',
  },
  {
    id: 'att-303',
    briefingSessionId: 'brf-202',
    userId: 'usr-normal-2',
    userName: 'Emily Wong',
    userEmail: 'emily.wong@acmecorp.com',
    departmentId: 'dept-eng',
    status: 'Absent',
    remarks: 'Unexplained absence, client call clash',
    markedByUserId: 'usr-super-eng',
    markedByName: 'David Chen',
    markedAt: '2026-07-28T15:00:00Z',
  },
  {
    id: 'att-304',
    briefingSessionId: 'brf-202',
    userId: 'usr-normal-5',
    userName: 'Robert Kim',
    userEmail: 'robert.kim@acmecorp.com',
    departmentId: 'dept-eng',
    status: 'Late',
    remarks: 'Joined 25 mins late',
    markedByUserId: 'usr-super-eng',
    markedByName: 'David Chen',
    markedAt: '2026-07-28T15:00:00Z',
  },
];

export const initialNotificationTemplates: NotificationTemplate[] = [
  {
    id: 'tmpl-reg',
    eventType: 'registration',
    name: 'New User Registration Confirmation',
    subjectTemplate: 'Welcome to LeavePlan & Attendance Hub - Account Registered',
    bodyTemplate: 'Dear {recipient_name},\n\nWelcome to LeavePlan & Attendance Hub! Your account has been successfully registered under the {department} department.\n\nDetails:\n- Email: {details}\n- Date: {date_time}\n\nYou can access your dashboard and submit leave requests or view briefing schedules at: {action_url}\n\nBest regards,\nCorporate Admin Team',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'tmpl-leave-sub',
    eventType: 'leave_submitted',
    name: 'Leave Request Submitted',
    subjectTemplate: 'Leave Request Submitted: {details}',
    bodyTemplate: 'Dear {recipient_name},\n\nYour leave request for {department} has been successfully submitted and is currently pending review.\n\nLeave Details:\n{details}\nDate & Duration: {date_time}\n\nTrack status: {action_url}',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'tmpl-leave-status',
    eventType: 'leave_status',
    name: 'Leave Request Status Changed',
    subjectTemplate: 'Leave Request Update: {details}',
    bodyTemplate: 'Dear {recipient_name},\n\nYour leave request status has been updated.\n\nDetails:\n{details}\nUpdated On: {date_time}\n\nView details: {action_url}',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'tmpl-brf-sched',
    eventType: 'briefing_scheduled',
    name: 'Briefing Session Scheduled',
    subjectTemplate: 'New Briefing Scheduled: {details}',
    bodyTemplate: 'Dear {recipient_name},\n\nA new mandatory briefing session has been scheduled for the {department} department.\n\nBriefing Title: {details}\nDate & Time: {date_time}\n\nJoin link & details: {action_url}',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'tmpl-brf-rem',
    eventType: 'briefing_reminder',
    name: 'Briefing Reminder (1 Day Before)',
    subjectTemplate: 'Reminder: Tomorrow Briefing Session - {details}',
    bodyTemplate: 'Dear {recipient_name},\n\nThis is a friendly reminder that your briefing session "{details}" for {department} is scheduled for tomorrow at {date_time}.\n\nPlease ensure your attendance: {action_url}',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'tmpl-followup',
    eventType: 'followup_briefing',
    name: 'Follow-up Briefing Scheduled',
    subjectTemplate: 'Follow-up Briefing Notice: {details}',
    bodyTemplate: 'Dear {recipient_name},\n\nDue to low attendance or user leave conflicts in the previous session, a follow-up briefing has been scheduled for {department}.\n\nTitle: {details}\nNew Date & Time: {date_time}\n\nPlease confirm participation: {action_url}',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'tmpl-att-marked',
    eventType: 'attendance_marked',
    name: 'Attendance Record Summary',
    subjectTemplate: 'Attendance Recorded: {details}',
    bodyTemplate: 'Dear {recipient_name},\n\nAttendance has been recorded for the briefing session "{details}" ({department}).\n\nMarking Date: {date_time}\n\nView attendance report: {action_url}',
    updatedAt: '2026-01-10T08:00:00Z',
  },
];

export const initialNotifications: Notification[] = [
  {
    id: 'notif-1',
    recipientUserId: 'usr-normal-1',
    title: 'Leave Request Approved',
    message: 'Your Annual Leave request for Aug 4 - Aug 6, 2026 has been approved by David Chen.',
    type: 'leave_status',
    isRead: false,
    actionUrl: '/leave-history',
    createdAt: '2026-07-21T14:30:00Z',
  },
  {
    id: 'notif-2',
    recipientUserId: 'usr-normal-1',
    title: 'New Briefing Scheduled',
    message: 'Q3 System Security & Compliance Briefing scheduled for Aug 5, 2026 at 09:30 AM.',
    type: 'briefing_scheduled',
    isRead: false,
    actionUrl: '/briefings',
    createdAt: '2026-07-25T10:00:00Z',
  },
];

export const initialEmailLogs: EmailLog[] = [
  {
    id: 'eml-1',
    recipientEmail: 'alex.rivera@acmecorp.com',
    recipientName: 'Alex Rivera',
    departmentName: 'Engineering & IT',
    subject: 'Leave Request Update: Annual Leave Approved',
    eventType: 'leave_status',
    contentHtml: '<p>Dear Alex Rivera,</p><p>Your leave request for Annual Leave from Aug 4 to Aug 6 has been <strong>Approved</strong>.</p>',
    sentAt: '2026-07-21T14:30:00Z',
    status: 'Sent',
  },
  {
    id: 'eml-2',
    recipientEmail: 'alex.rivera@acmecorp.com',
    recipientName: 'Alex Rivera',
    departmentName: 'Engineering & IT',
    subject: 'New Briefing Scheduled: Q3 System Security & Compliance Briefing',
    eventType: 'briefing_scheduled',
    contentHtml: '<p>Dear Alex Rivera,</p><p>A new briefing session has been scheduled for Aug 5, 2026 at 09:30 AM.</p>',
    sentAt: '2026-07-25T10:00:00Z',
    status: 'Sent',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'aud-1',
    actionType: 'Registration',
    performedByUserId: 'usr-normal-1',
    performedByName: 'Alex Rivera',
    performedByEmail: 'alex.rivera@acmecorp.com',
    timestamp: '2026-02-01T09:00:00Z',
    oldValue: '',
    newValue: 'Registered user alex.rivera@acmecorp.com in Engineering & IT',
    remarks: 'Google OAuth Signup',
  },
  {
    id: 'aud-2',
    actionType: 'Leave Submission',
    performedByUserId: 'usr-normal-1',
    performedByName: 'Alex Rivera',
    performedByEmail: 'alex.rivera@acmecorp.com',
    timestamp: '2026-07-20T10:00:00Z',
    oldValue: '',
    newValue: 'Submitted Annual Leave (2026-08-04 to 2026-08-06)',
    remarks: 'Status: Submitted',
  },
  {
    id: 'aud-3',
    actionType: 'Attendance Submission',
    performedByUserId: 'usr-super-eng',
    performedByName: 'David Chen',
    performedByEmail: 'david.chen@acmecorp.com',
    timestamp: '2026-07-28T15:00:00Z',
    oldValue: '',
    newValue: 'Submitted attendance for DevOps Infrastructure Update Briefing (4 users)',
    remarks: 'Attendance Rate: 50%',
  },
];
